### ISSUE TITLE
列出目录和下载凡是带空格的文件夹好像都失效了

### ISSUE THREAD

**Issue by tricky95** [PeterDing/BaiduPCS-Py#116]
前几天可以用，这两天出现问题了。不带空格的（如"PPT模板"）文件夹都可以ls出文件，而带空格的（“PPT 模板”）文件夹无法ls出来。包括download也出现同样问题。

**Comment by PeterDing** [comment]
试试加引号 `BaiduPCS-Py l '/a b'`

**Comment by tricky95** [comment]
没事了，加引号mac可以，win莫名其妙不行。
