### ISSUE TITLE
求教大佬们，同步本地目录到网盘的命令，如何显示进度？

### ISSUE THREAD

**Issue by holmes8600** [PeterDing/BaiduPCS-Py#120]
--no-show-progress, --NP   看文档说这个是不显示上传进度，
请问应该如何使用命令才可以显示同步的进度？
 这个参数我测试来测试去都不知道怎么用，希望大佬指点下 先谢谢了

**Comment by PeterDing** [comment]
`upload` 和 `sync` 命令都默认显示上传进度。如果不需要显示上传进度才用 `--NP`。

不过，最近baidu更新了秒传的接口，目前版本已经不能用 `upload` 和 `sync` 命令了。等待下个版本修复吧。
最近可以换[阿里网盘工具](https://github.com/PeterDing/AliPCS-Py)试试。

**Comment by holmes8600** [comment]
> `upload` 和 `sync` 命令都默认显示上传进度。如果不需要显示上传进度才用 `--NP`。
> 
> 不过，最近baidu更新了秒传的接口，目前版本已经不能用 `upload` 和 `sync` 命令了。等待下个版本修复吧。 最近可以换[阿里网盘工具](https://github.com/PeterDing/AliPCS-Py)试试。

谢谢回答。我测试貌似小文件可以上传，大的文件上传没反应，具体我再等等更新吧。   阿里网盘我试过了，但是我太小白添加账号我都添加不明白。
首先就是网页里找不到refresh_token， 后面找了个网页专门获取这个算是可以了，但是还需要openapi_refresh_token，然后还有openapi client id，openapi client secret，openapi client server，没搞明白这些个是要去哪里获取。
