### ISSUE TITLE
使用BaiduPCS-Py，分享文件时遇到错误

### ISSUE THREAD

**Issue by aadd445aadda** [PeterDing/BaiduPCS-Py#15]
`
from baidupcs_py.baidupcs import BaiduPCSApi

api = BaiduPCSApi(bduss=bduss, cookies=cookies)

print(api.share('/997.zip'))
`

/usr/local/lib/python3.7/dist-packages/baidupcs_py/baidupcs/errors.py in check(*args, **kwargs)
    148 
    149         if err:
--> 150             raise err
    151         return info
    152 
BaiduPCSError: error_code: -6, message: 请重新登录

已经确定cookie中有STOKEN 值
在上传成功后，进行分享，但是会出现‘请重新登录’提示

**Comment by PeterDing** [comment]
我没有遇到过这个错误。可能是你用 `api.share` 太频繁了。

你重新从 pan.baidu.com 获取 cookies 试试。

**Comment by aadd445aadda** [comment]
重新获取cookie，然后分享，还是 一样会出现'请重新登录'提示
更换另一个帐号之后，还是出现一样的情况
请给一个标准的api用法，因为我是看着源码调试的 很可能是 参数，我填写错误了

**Comment by PeterDing** [comment]
你使用的 `api.share` 参数没错。

请先将 BaiduPCS-Py 升级到最新版本，再用运行命令 `LOG_LEVEL=DEBUG BaiduPCS-Py share /somepath`。如果出错，贴出错误信息，如果没有出错，贴出你使用 api 的代码逻辑（不需要贴cookies），方便我重现这个错误。

**Comment by aadd445aadda** [comment]
```
from baidupcs_py.baidupcs import BaiduPCSApi

api = BaiduPCSApi(bduss=bduss, cookies=cookies)
print(api.user_info())

# 建立记事本
with open('997.txt', "a")as f:
    f.write('9999')

# 上传记事本
with open('997.txt', "rb")as f:
    print(api.upload_file(f,remotepath='/997.txt'))

# 分享记事本
print(api.share("/997.txt"))
```

```
BaiduPCSError                             Traceback (most recent call last)
<ipython-input-11-66415abcf80d> in <module>()
      8 
      9 # 分享记事本
---> 10 print(api.share("/997.txt"))

1 frames
/usr/local/lib/python3.7/dist-packages/baidupcs_py/baidupcs/errors.py in check(*args, **kwargs)
    148 
    149         if err:
--> 150             raise err
    151         return info
    152 

BaiduPCSError: error_code: -6, message: 请重新登录
```

**Comment by PeterDing** [comment]
确实存在这个问题。在使用了很长时间的 cookies 上复现了这个错误。

之后，我重新在 pan.baidu.com 登录后，获取了新的 cookies，用这个 cookies 就没有报错了。

**Comment by aadd445aadda** [comment]
非常感谢，已解决
清理cookie之后 重新登录即可
