### ISSUE TITLE
Building wheel for BaiduPCS-Py (PEP 517): finished with status 'error'

### ISSUE THREAD

**Issue by ldj46118** [PeterDing/BaiduPCS-Py#17]
安装提示错误
Building wheel for BaiduPCS-Py (PEP 517): started
  Building wheel for BaiduPCS-Py (PEP 517): finished with status 'error'
Failed to build BaiduPCS-Py

**Comment by PeterDing** [comment]
请贴出完整的错误输出，上面的信息太少。

**Comment by ldj46118** [comment]
已回复邮箱，请帮忙查看！

**Comment by ldj46118** [comment]
请看附件

**Comment by ldj46118** [comment]
请看附件

**Comment by PeterDing** [comment]
在 Windows 上，BaiduPCS-Py 依赖 [Microsoft C++ Build Tools](https://visualstudio.microsoft.com/visual-cpp-build-tools/)。

在安装 BaiduPCS-Py 前，请先安装 [Microsoft C++ Build Tools](https://visualstudio.microsoft.com/visual-cpp-build-tools/)，再在其中勾选 `C++ 生成工具` 并安装。完成后即可安装 BaiduPCS-Py。

**Comment by OnePerson2020** [comment]
请问Ubuntu也报这样的错要怎么解决呀？
  ERROR: Failed building wheel for BaiduPCS-Py
Failed to build BaiduPCS-Py
ERROR: Could not build wheels for BaiduPCS-Py which use PEP 517 and cannot be installed directly

**Comment by PeterDing** [comment]
@OnePerson2020 需要 `pip3 install --upgrade pip setuptools wheel`

**Comment by OnePerson2020** [comment]
这个命令试过了，但是报相同的错欸。







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PeterDing/BaiduPCS-Py"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月16日(星期六) 上午9:24
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PeterDing/BaiduPCS-Py] Building wheel for BaiduPCS-Py (PEP 517): finished with status 'error' (#17)





 
@OnePerson2020 需要 pip3 install --upgrade pip setuptools wheel

**Comment by nikerck** [comment]
> 这个命令试过了，但是报相同的错欸。
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "PeterDing/BaiduPCS-Py" ***@***.***&gt;; 发送时间:&nbsp;2021年10月16日(星期六) 上午9:24 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [PeterDing/BaiduPCS-Py] Building wheel for BaiduPCS-Py (PEP 517): finished with status 'error' (#17) @OnePerson2020 需要 pip3 install --upgrade pip setuptools wheel — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

我在centos8遇到跟你同样问题。

```sh
ERROR: Could not build wheels for BaiduPCS-Py which use PEP 517 and cannot be installed directly

```

我通过以下方式解决

```sh
python -m pip install --upgrade pip
python -m pip install --upgrade setuptools
```



后续我遇到第二个问题

```sh
ERROR: Failed building wheel for BaiduPCS-Py
ERROR: Could not build wheels for BaiduPCS-Py, which is required to install pyproject.toml-based projects
```
我往上寻找发现，因为缺少Python.h

```
fatal error: Python.h: No such file or directory
```

通过安装 python-dev 或 python-devel 包解决

```sh
dnf install python39-devel  # 我这里用的是python3.9
```
希望对你有帮助
