### ISSUE TITLE
[Feature request] 可以提供一个download_dir api 的同步版本吗？

### ISSUE THREAD

**Issue by IWANABETHATGUY** [PeterDing/BaiduPCS-Py#18]
```py
download.download_dir(self.api,
        latest_file.path,
        download_path,
        recursive=True)
```
遇到一个需求，需要再将某个百度链接转存完以后做一些逻辑，当前的api 没有提供回调函数，或者同步的版本，可以麻烦作者提供一个相关的api吗？或者有没有什么好的解决的方法呢？

**Comment by PeterDing** [comment]
不太清楚你描述的需求。api 都不会去实现业务逻辑。

-----

如果你想对转存后的文件进行处理，你需要知道存了那些文件 (`BaiduPCSApi.shared_paths` 和 `BaiduPCSApi.list_shared_paths`) 或者转存到特定的目录下再获取目录下的文件。这之后再进行你的逻辑业务。

**Comment by IWANABETHATGUY** [comment]
因为这个api 是异步的，不知道这个会再什么时候转存完成，是否出错

**Comment by PeterDing** [comment]
`BaiduPCSApi.transfer_shared_paths` 是同步的，如果转存出错会抛出异常的。

可以看看这个：
https://github.com/PeterDing/BaiduPCS-Py/blob/311473296310a2d0b4df9dcf1bfa33c58968e8e3/baidupcs_py/commands/share.py#L79-L95
