### ISSUE TITLE
一直无法在Windows10安装

### ISSUE THREAD

**Issue by aadd445aadda** [PeterDing/BaiduPCS-Py#20]
```
  ERROR: Failed building wheel for baidupcs-py
ERROR: Could not build wheels for baidupcs-py which use PEP 517 and cannot be installed directly
```
Windows10 64位系统
python3.8
pip21.0.1
Windows折腾很久无法安装，非常难受

**Comment by IWANABETHATGUY** [comment]
麻烦把完整的error 日志贴一下吧，我是装了一个windows-mscc-build-tool 编译成功的

**Comment by PeterDing** [comment]
在 Windows 上，BaiduPCS-Py 依赖 [Microsoft C++ Build Tools](https://visualstudio.microsoft.com/visual-cpp-build-tools/)。

在安装 BaiduPCS-Py 前，请先安装 [Microsoft C++ Build Tools](https://visualstudio.microsoft.com/visual-cpp-build-tools/)，再在其中勾选 `C++ 生成工具` 并安装。完成后即可安装 BaiduPCS-Py。
