### ISSUE TITLE
ERROR System ERROR 'userid'

### ISSUE THREAD

**Issue by IWANABETHATGUY** [PeterDing/BaiduPCS-Py#21]
v0.6.4) System ERROR: 'shareid'

**Comment by PeterDing** [comment]
请参考[这里](https://github.com/PeterDing/BaiduPCS-Py/blob/master/.github/ISSUE_TEMPLATE/bug-report---bug---.md)，清楚的描述你遇到的问题。在第一个 comment 中修改。

**Comment by IWANABETHATGUY** [comment]
> 请参考[这里](https://github.com/PeterDing/BaiduPCS-Py/blob/master/.github/ISSUE_TEMPLATE/bug-report---bug---.md)，清楚的描述你遇到的问题。在第一个 comment 中修改。

我有一个pr 可以解决这个问题，亲测有效

**Comment by PeterDing** [comment]
我不知道你怎么使用的，遇到什么问题。无清楚描述的 issue 和 pull request 都会关闭。
