### ISSUE TITLE
保存分享出错

### ISSUE THREAD

**Issue by 451835239** [PeterDing/BaiduPCS-Py#24]
DEBUG=1 BaiduPCS-Py save -p nefb https://pan.baidu.com/s/1CrpqjwIgqUVT_bBCV0aWXw   /
(v0.6.9) System ERROR:
System ERROR  系统信息没有任何输出内容，辛苦解答

**Comment by PeterDing** [comment]
在 v0.6.10 版，问题已修复。

**Comment by ldj46118** [comment]
baidupcs-py share  /2019/*.rar 提示 system error ：“list”

**Comment by PeterDing** [comment]
@ldj46118  `share` 命令不支持通配符“*”

**Comment by ldj46118** [comment]
不是通配符，就是在win7系统 baidupcs-py share /2019/1.rar  提示system error ：“list” 
就是不会分享文件，详细的如何使用呢？

**Comment by ldj46118** [comment]
BaiduPCS-Py save -p nefb https://pan.baidu.com/s/1CrpqjwIgqUVT_bBCV0aWXw /  提示错误 System ERROR:‘shareid’

**Comment by PeterDing** [comment]
> BaiduPCS-Py save -p nefb https://pan.baidu.com/s/1CrpqjwIgqUVT_bBCV0aWXw / 提示错误 System ERROR:‘shareid’

的问题已经在 0.6.11 版本中修复。`share` 的问题请新开一个 issue。

**Comment by ldj46118** [comment]
如果分享文件，路径带空格或者特殊字符 ，可以实现分享吗？

**Comment by ldj46118** [comment]
share那个成功了，没有成功的是因为文件文件名包含空格

**Comment by ldj46118** [comment]
比如这个网盘的分享链接，再转存到这个网盘的其他文件夹，会提示has be  in，不能转存成功

**Comment by PeterDing** [comment]
如果要转存的文件在要保存的目录中已经存在，则不会再保存。

**Comment by ldj46118** [comment]
分享链接是A盘的，但是不在同一个文件夹下，也不会保存吗？

**Comment by 451835239** [comment]
(v0.6.11) ERROR: BaiduPCSError: error_code: 105, message: 啊哦，链接错误没找到文件，请打开正确的分享链接

**Comment by 451835239** [comment]
@PeterDing    一直报提取码错误

**Comment by 451835239** [comment]
@PeterDing
