### ISSUE TITLE
如果分享文件，路径带空格或者特殊字符 ，可以实现分享吗？

### ISSUE THREAD

**Issue by ldj46118** [PeterDing/BaiduPCS-Py#25]
baidupcs-go可以实现空格或者特殊符号的分享，用通配符‘’，大佬可以加上吗？

**Comment by PeterDing** [comment]
分享的路径中的字符不会做任何处理。确保要分享的路径输入正确即可。

**Comment by ldj46118** [comment]
您测试一下，分享的路径或者文件名有空格的，或者有其他特殊字符的，就不能实现分享

**Comment by PeterDing** [comment]
待空格的路径用 `""`，如 `"/path/a b/e d"`

**Comment by ldj46118** [comment]
成功了！谢谢！
