### ISSUE TITLE
保存分享报错 

### ISSUE THREAD

**Issue by 451835239** [PeterDing/BaiduPCS-Py#28]
已经升级最新版本，save 还是会出现报错情况      
(v0.6.11) ERROR: BaiduPCSError: error_code: 105, message: 啊哦，链接错误没找到文件，请打开正确的分享链接
BaiduPCS-Py save -p nefb https://pan.baidu.com/s/1CrpqjwIgqUVT_bBCV0aWXw /

**Comment by 451835239** [comment]
@PeterDing    能否帮忙解答一下？

**Comment by PeterDing** [comment]
请务必确保你的描述依从 [bug issus 模板](https://github.com/PeterDing/BaiduPCS-Py/blob/master/.github/ISSUE_TEMPLATE/bug-report---bug---.md)

**Comment by 451835239** [comment]
/usr/local/lib/python3.9/site-packages/baidupcs_py/app/app.py:101 in wrap                        │
│                                                                                                  │
│     98 │   @wraps(func)                                                                          │
│     99 │   def wrap(*args, **kwargs):                                                            │
│    100 │   │   try:                                                                              │
│ ❱  101 │   │   │   return func(*args, **kwargs)                                                  │
│    102 │   │   except BaiduPCSError as err:                                                      │
│    103 │   │   │   _exit_progress_bar()                                                          │
│                                                                                                  │
│ /usr/local/lib/python3.9/site-packages/baidupcs_py/app/app.py:159 in wrap                        │
│                                                                                                  │
│    156 │   │   ctx = args[0]                                                                     │
│    157 │   │   user_ids = _user_ids(ctx)                                                         │
│    158 │   │   if not user_ids:                                                                  │
│ ❱  159 │   │   │   return func(*args, **kwargs)                                                  │
│    160 │   │                                                                                     │
│    161 │   │   am = ctx.obj.account_manager                                                      │
│    162 │   │   for user_id in user_ids:                                                          │
│                                                                                                  │
│ /usr/local/lib/python3.9/site-packages/baidupcs_py/app/app.py:1539 in save                       │
│                                                                                                  │
│   1536 │   pwd = _pwd(ctx)                                                                       │
│   1537 │   remotedir = join_path(pwd, remotedir)                                                 │
│   1538 │                                                                                         │
│ ❱ 1539 │   _share.save_shared(                                                                   │
│   1540 │   │   api,                                                                              │
│   1541 │   │   shared_url,                                                                       │
│   1542 │   │   remotedir,                                                                        │
│                                                                                                  │
│ /usr/local/lib/python3.9/site-packages/baidupcs_py/commands/share.py:51 in save_shared           │
│                                                                                                  │
│    48 │                                                                                          │
│    49 │   # Vertify with password                                                                │
│    50 │   if password:                                                                           │
│ ❱  51 │   │   api.access_shared(shared_url, password, show_vcode=show_vcode)                     │
│    52 │                                                                                          │
│    53 │   shared_paths = deque(api.shared_paths(shared_url))                                     │
│                                                                                                  │
│ /usr/local/lib/python3.9/site-packages/baidupcs_py/baidupcs/api.py:282 in access_shared          │
│                                                                                                  │
│   279 │   │   │   │   return                                                                     │
│   280 │   │   │   except BaiduPCSError as err:                                                   │
│   281 │   │   │   │   if err.error_code not in (-9, -62):                                        │
│ ❱ 282 │   │   │   │   │   raise err                                                              │
│   283 │   │   │   │   if show_vcode:                                                             │
│   284 │   │   │   │   │   if err.error_code == -62:  # -62: '可能需要输入验证码'                 │
│   285 │   │   │   │   │   │   print("[yellow]Need vcode![/yellow]")                              │
│                                                                                                  │
│ /usr/local/lib/python3.9/site-packages/baidupcs_py/baidupcs/api.py:278 in access_shared          │
│                                                                                                  │
│   275 │   ):                                                                                     │
│   276 │   │   while True:                                                                        │
│   277 │   │   │   try:                                                                           │
│ ❱ 278 │   │   │   │   self._baidupcs.access_shared(shared_url, password, vcode_str, vcode)       │
│   279 │   │   │   │   return                                                                     │
│   280 │   │   │   except BaiduPCSError as err:                                                   │
│   281 │   │   │   │   if err.error_code not in (-9, -62):                                        │
│                                                                                                  │
│ /usr/local/lib/python3.9/site-packages/baidupcs_py/baidupcs/errors.py:150 in check               │
│                                                                                                  │
│   147 │   │   │   err = parse_errno(error_code)                                                  │
│   148 │   │                                                                                      │
│   149 │   │   if err:                                                                            │
│ ❱ 150 │   │   │   raise err                                                                      │
│   151 │   │   return info                                                                        │
│   152 │                                                                                          │
│   153 │   return check

**Comment by 451835239** [comment]
![image](https://user-images.githubusercontent.com/18321751/111933365-44766900-8afa-11eb-8984-92bf9ee7abb6.png)

**Comment by PeterDing** [comment]
@451835239 https://pan.baidu.com/s/1CrpqjwIgqUVT_bBCV0aWXw 已经失效

**Comment by 451835239** [comment]
感谢   已经解决
