### ISSUE TITLE
保存分享出错

### ISSUE THREAD

**Issue by bsdcpp** [PeterDing/BaiduPCS-Py#3]
感谢大佬分享这么给力的工具，辛苦。
我在用保存共享链接的时候遇到错误：
`BaiduPCS-Py save -p s9vd https://pan.baidu.com/s/1adS0qazDDcDjx7NP_HNLJQ  /
ERROR: BaiduPCSError: BaiduPCS._request `

尝试了几个链接都有这问题，谢谢

**Comment by PeterDing** [comment]
@bsdcpp 我无法复现这个错误。

<img width="625" alt="Screen Shot 2021-01-24 at 11 34 35 AM" src="https://user-images.githubusercontent.com/670690/105620450-57412a00-5e38-11eb-9e19-eb867eb6c5a4.png">

-----------

你可以用下面命令，打印出错信息。

```
DEBUG=1 BaiduPCS-Py save -p s9vd https://pan.baidu.com/s/1adS0qazDDcDjx7NP_HNLJQ /
```

**Comment by bsdcpp** [comment]
感谢回复，具体错误如下`❯ 
❯ DEBUG=1 BaiduPCS-Py save -p s9vd https://pan.baidu.com/s/1adS0qazDDcDjx7NP_HNLJQ /
ERROR: BaiduPCSError: BaiduPCS._request
╭─────────────── Traceback (most recent call last) ────────────────╮│ /home/jervis/.virtualenvs/spiders/lib/python3.8/site-packages/ba ││ idupcs_py/baidupcs/pcs.py:152 in _request                        ││                                                                  ││   149 │   │   │   headers["Content-Type"] = data.content_type    ││   150 │   │                                                      ││   151 │   │   try:                                               ││ ❱ 152 │   │   │   resp = self._session.request(                  ││   153 │   │   │   │   method.value,                              ││   154 │   │   │   │   url,                                       ││   155 │   │   │   │   params=params,                             ││                                                                  ││ /home/jervis/.virtualenvs/spiders/lib/python3.8/site-packages/re ││ quests/sessions.py:542 in request                                ││                                                                  ││   539 │   │   │   'allow_redirects': allow_redirects,            ││   540 │   │   }                                                  ││   541 │   │   send_kwargs.update(settings)                       ││ ❱ 542 │   │   resp = self.send(prep, **send_kwargs)              ││   543 │   │                                                      ││   544 │   │   return resp                                        ││                                                                  ││ /home/jervis/.virtualenvs/spiders/lib/python3.8/site-packages/re ││ quests/sessions.py:677 in send                                   ││                                                                  ││   674 │   │   if allow_redirects:                                ││   675 │   │   │   # Redirect resolving generator.                ││   676 │   │   │   gen = self.resolve_redirects(r, request, **kwa ││ ❱ 677 │   │   │   history = [resp for resp in gen]               ││   678 │   │   else:                                              ││   679 │   │   │   history = []                                   ││                                                                  ││ /home/jervis/.virtualenvs/spiders/lib/python3.8/site-packages/re ││ quests/sessions.py:677 in <listcomp>                             ││                                                                  ││   674 │   │   if allow_redirects:                                ││   675 │   │   │   # Redirect resolving generator.                ││   676 │   │   │   gen = self.resolve_redirects(r, request, **kwa ││ ❱ 677 │   │   │   history = [resp for resp in gen]               ││   678 │   │   else:                                              ││   679 │   │   │   history = []                                   ││                                                                  ││ /home/jervis/.virtualenvs/spiders/lib/python3.8/site-packages/re ││ quests/sessions.py:166 in resolve_redirects                      ││                                                                  ││   163 │   │   │   │   resp.raw.read(decode_content=False)        ││   164 │   │   │                                                  ││   165 │   │   │   if len(resp.history) >= self.max_redirects:    ││ ❱ 166 │   │   │   │   raise TooManyRedirects('Exceeded {} redire ││   167 │   │   │                                                  ││   168 │   │   │   # Release the connection back into the pool.   ││   169 │   │   │   resp.close()                                   │╰──────────────────────────────────────────────────────────────────╯TooManyRedirects: Exceeded 30 redirects.

The above exception was the direct cause of the following exception:
╭─────────────── Traceback (most recent call last) ────────────────╮│ /home/jervis/.virtualenvs/spiders/lib/python3.8/site-packages/ba ││ idupcs_py/app/app.py:66 in wrap                                  ││                                                                  ││    63 │   @wraps(func)                                           ││    64 │   def wrap(*args, **kwargs):                             ││    65 │   │   try:                                               ││ ❱  66 │   │   │   return func(*args, **kwargs)                   ││    67 │   │   except BaiduPCSError as err:                       ││    68 │   │   │   print(f"[bold red]ERROR[/bold red]: BaiduPCSEr ││    69 │   │   │   if DEBUG:                                      ││                                                                  ││ /home/jervis/.virtualenvs/spiders/lib/python3.8/site-packages/ba ││ idupcs_py/app/app.py:896 in save                                 ││                                                                  ││   893 │   pwd = _pwd(ctx)                                        ││   894 │   remotedir = join_path(pwd, remotedir)                  ││   895 │                                                          ││ ❱ 896 │   _share.save_shared(                                    ││   897 │   │   api,                                               ││   898 │   │   shared_url,                                        ││   899 │   │   remotedir,                                         ││                                                                  ││ /home/jervis/.virtualenvs/spiders/lib/python3.8/site-packages/ba ││ idupcs_py/commands/share.py:55 in save_shared                    ││                                                                  ││    52 │   if password:                                           ││    53 │   │   api.access_shared(shared_url, password, show_vcode ││    54 │                                                          ││ ❱  55 │   shared_paths = deque(api.shared_paths(shared_url))     ││    56 │                                                          ││    57 │   # Record the remotedir of each shared_path             ││    58 │   _remotedirs: Dict[PcsSharedPath, str] = {}             ││                                                                  ││ /home/jervis/.virtualenvs/spiders/lib/python3.8/site-packages/ba ││ idupcs_py/baidupcs/api.py:236 in shared_paths                    ││                                                                  ││   233 │   │   return self._baidupcs.get_vcode_img(vcode_img_url, ││   234 │                                                          ││   235 │   def shared_paths(self, shared_url: str) -> List[PcsSha ││ ❱ 236 │   │   info = self._baidupcs.shared_paths(shared_url)     ││   237 │   │   uk = info["uk"]                                    ││   238 │   │   share_id = info["shareid"]                         ││   239 │   │   bdstoken = info["bdstoken"]                        ││                                                                  ││ /home/jervis/.virtualenvs/spiders/lib/python3.8/site-packages/ba ││ idupcs_py/baidupcs/errors.py:132 in check                        ││                                                                  ││   129 │                                                          ││   130 │   @wraps(func)                                           ││   131 │   def check(*args, **kwargs):                            ││ ❱ 132 │   │   info = func(*args, **kwargs)                       ││   133 │   │   error_code = info.get("errno")                     ││   134 │   │   if error_code is None:                             ││   135 │   │   │   error_code = info.get("error_code")            ││                                                                  ││ /home/jervis/.virtualenvs/spiders/lib/python3.8/site-packages/ba ││ idupcs_py/baidupcs/pcs.py:662 in shared_paths                    ││                                                                  ││   659 │   │   Call `BaiduPCS.access_share` before calling the fu ││   660 │   │   """                                                ││   661 │   │                                                      ││ ❱ 662 │   │   resp = self._request(Method.Get, shared_url, param ││   663 │   │   html = resp.text                                   ││   664 │   │                                                      ││   665 │   │   m = re.search(r"yunData.setData\((.+?)\);", html)  ││                                                                  ││ /home/jervis/.virtualenvs/spiders/lib/python3.8/site-packages/ba ││ idupcs_py/baidupcs/pcs.py:163 in _request                        ││                                                                  ││   160 │   │   │   )                                              ││   161 │   │   │   return resp                                    ││   162 │   │   except Exception as err:                           ││ ❱ 163 │   │   │   raise BaiduPCSError("BaiduPCS._request", cause ││   164 │                                                          ││   165 │   def _request_get(                                      ││   166 │   │   self,                                              │╰──────────────────────────────────────────────────────────────────╯BaiduPCSError: BaiduPCS._request
❯ python -V
Python 3.8.6
`

**Comment by bsdcpp** [comment]
![0B409E5B-30A1-4307-8243-DE505360FC50](https://user-images.githubusercontent.com/1034557/105622764-01c44780-5e4f-11eb-92f6-d9665382ce89.jpeg)
如图，麻烦看下

**Comment by PeterDing** [comment]
@bsdcpp 应该是你的cookies里没有 `STOKEN` 值。这会让 `share` 和 `save` 命令无法工作。

我已经把这个警告加入了 v0.3.8

**Comment by bsdcpp** [comment]
> @bsdcpp 应该是你的cookies里没有 `STOKEN` 值。这会让 `share` 和 `save` 命令无法工作。
> 
> 我已经把这个警告加入了 v0.3.8

强，解决了。另外还有个问题请教：
使用了短链接改写后的url无法识别，比如http://t.cn/A654c4bM 密码 ac5s
即使我在浏览器转成了百度的链接https://pan.baidu.com/wap/init?surl=dRbOl5F3OC0KykHEwCJCSg也不行。
麻烦指点下。谢谢

**Comment by PeterDing** [comment]
你可以把 https://pan.baidu.com/wap/init?surl=dRbOl5F3OC0KykHEwCJCSg 变为 https://pan.baidu.com/s/1dRbOl5F3OC0KykHEwCJCSg 就好。

**Comment by bsdcpp** [comment]
> 你可以把 https://pan.baidu.com/wap/init?surl=dRbOl5F3OC0KykHEwCJCSg 变为 https://pan.baidu.com/s/1dRbOl5F3OC0KykHEwCJCSg 就好。

万分感谢，成功了，神器。

**Comment by 451835239** [comment]
@bsdcpp  @PeterDing    保存其他用户分享的链接  BaiduPCS-Py save  需要验证码

**Comment by ldj46118** [comment]
DEBUG=1 BaiduPCS-Py save -p s9vd https://pan.baidu.com/s/1adS0qazDDcDjx7NP_HNLJQ /

为啥我在dos下输入这个命令，会提示debug既不是内部命令也不是外部命令
