### ISSUE TITLE
MACOS 无法贴入 Cookie  

### ISSUE THREAD

**Issue by cryzlasm** [PeterDing/BaiduPCS-Py#4]
MACOS 无法贴入 Cookie  能否使用解析文件的方式?

还有既然已经贴 Cookie 了 能否从 Cookie 中拆出 bduss?

**Comment by PeterDing** [comment]
@cryzlasm 只输入 bduss 也可以用，但是不能 `save` 和 `share`

如果无法粘贴，可以用

```
BaiduPCS-Py useradd --cookies "cookies 值" --bduss "bduss 值"
```

**Comment by cryzlasm** [comment]
好的
