### ISSUE TITLE
ERROR: BaiduPCSError: error_code: 31045, message: 用户不存在

### ISSUE THREAD

**Issue by zerofo** [PeterDing/BaiduPCS-Py#46]
0.6.20 版本
刷新过网页了。。。   输入 co 后(Cook***:  冒号后一直到第一个分号内容  BAIDUID前)   
显示
`ERROR: BaiduPCSError: error_code: 31045, message: 用户不存在`

**Comment by zerofo** [comment]
好像又开始了
百度更新了
BDUSS没了,, 
变 
BDUSS_BFESS

**Comment by PeterDing** [comment]
你再看看，BDUSS 是有的。

**Comment by xyb** [comment]
我也碰到了这个问题，要退出并重新登录之后，才能看到 BDUSS。
