### ISSUE TITLE
保存分享链接，保存不成功，明明远程地址设定了，还一直提示Missing argument 'REMOTEDIR'.

### ISSUE THREAD

**Issue by xiaowang-edu** [PeterDing/BaiduPCS-Py#48]
错误提示：

Usage: BaiduPCS-Py save [OPTIONS] SHARED_URL REMOTEDIR
Try 'BaiduPCS-Py save --help' for help.

Error: Missing argument 'REMOTEDIR'.
'parentPath' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

**Comment by PeterDing** [comment]
贴一下你出错的命令。

**Comment by xiaowang-edu** [comment]
你好，谢谢您的回复

刚才我把电脑重启了下，重复上次失败的操作命令，现在又好了。不知道是不是安装完后得重新启动的原因。



***@***.***
 
发件人： Peter Ding
发送时间： 2021-06-18 14:41
收件人： PeterDing/BaiduPCS-Py
抄送： xiaowang; Author
主题： Re: [PeterDing/BaiduPCS-Py] 保存分享链接，保存不成功，明明远程地址设定了，还一直提示Missing argument 'REMOTEDIR'. (#48)
贴一下你出错的命令。
