### ISSUE TITLE
列出其他用户分享链接中的文件

### ISSUE THREAD

**Issue by yzf123456** [PeterDing/BaiduPCS-Py#52]
你好，项目中列出其他用户分享链接中的文件功能是不是不可用？能更新一下吗？

**Comment by PeterDing** [comment]
我用我的帐号测试了， v0.6.23 版本的 `lsp` 命令能正常使用。

如果遇到出错的问题，请依照 issus bug 模板进行说明。

**Comment by yzf123456** [comment]
<img width="560" alt="截屏2021-07-10 下午12 47 56" src="https://user-images.githubusercontent.com/43875437/125152108-18e8be80-e17d-11eb-866f-7f1cb5d22128.png">
你好，我尝试了一下，没有找到v.6.23版本，请我是我哪里出了问题？

**Comment by PeterDing** [comment]
你试试 `pip3 install -i https://pypi.tuna.tsinghua.edu.cn/simple BaiduPCS-Py --upgrade`

**Comment by yzf123456** [comment]
> 你试试 `pip3 install -i https://pypi.tuna.tsinghua.edu.cn/simple BaiduPCS-Py --upgrade`

你好，我试了一下还是不行，这应该和我用了Python3.6有关，然后我安装了Python3.8，可以了。谢谢
