### ISSUE TITLE
有计划支持wap版分享链接吗

### ISSUE THREAD

**Issue by Aixzk** [PeterDing/BaiduPCS-Py#55]
例如链接：https://pan.baidu.com/wap/init?surl=OOHZMcm-rUQA4piSgtWBiw  提取码：hmts

**列出其他用户分享链接中的文件**
> `BaiduPCS-Py listsharedpaths -p hmts http://pan.baidu.com/wap/init?surl=OOHZMcm-rUQA4piSgtWBiw`
> (v0.6.20) ERROR: BaiduPCSError: error_code: 105, message: 啊哦，链接错误没找到文件，请打开正确的分享链接

**保存其他用户分享的链接**
> `BaiduPCS-Py save -p hmts http://pan.baidu.com/wap/init?surl=OOHZMcm-rUQA4piSgtWBiw /`
> (v0.6.20) ERROR: BaiduPCSError: error_code: 105, message: 啊哦，链接错误没找到文件，请打开正确的分享链接

直接用浏览器打开这个分享链接后是手机版页面，输入正确的提取码并提交后跳转到新的网址：
`https://pan.baidu.com/s/1OOHZMcm-rUQA4piSgtWBiw?dp-logid=20610200123498120001#list/path=%2F`

这时候再用新的网址代替上面命令的WAP版链接就能正常工作：
> `BaiduPCS-Py listsharedpaths -p hmts https://pan.baidu.com/s/1OOHZMcm-rUQA4piSgtWBiw?dp-logid=20610200123498120001#list/path=%2F`
>                     Size Path
> ──────────────────────────────────────────────────────────────────────────
> \- 220.4 MB 231147936 /sharelink3378067569-108609370664595/WePE_64_V2.1.exe
> \-    194 B       194 /微PE工具箱/V2.1.1/WePE_64_V2.1.exe_MD5.txt

不知道有没有计划支持？

**Comment by PeterDing** [comment]
这个可以有，下一版会加入。

**Comment by PeterDing** [comment]
已经在 `v0.6.25` 中支持。

**Comment by Aixzk** [comment]
感谢！！太给力了
