### ISSUE TITLE
本地打包执行

### ISSUE THREAD

**Issue by yzf123456** [PeterDing/BaiduPCS-Py#63]
你好，我自己修改了一点代码，然后计划安装本地下载的代码，但是按照您提供的教程，每次都是安装github上最新的版本。请问，我应该基于本地代码进行安装？谢谢。

我尝试了Python setup.py install的方式，但好像没有成功。

**Comment by PeterDing** [comment]
你可以以下面的步骤构建自己的包。

1. `pip3 install poetry`
2. `rm -fr dist`
3. `poetry build -f sdist`

之后，你可以在 dist/ 中找到构建好的包。

**Comment by yzf123456** [comment]
> 你可以以下面的步骤构建自己的包。
> 
> 1. `pip3 install poetry`
> 2. `rm -fr dist`
> 3. `poetry build -f sdist`
> 
> 之后，你可以在 dist/ 中找到构建好的包。

谢谢，已解决。
