### ISSUE TITLE
下载速度慢的问题

### ISSUE THREAD

**Issue by Aixzk** [PeterDing/BaiduPCS-Py#66]
从昨日下午五点过后无论用 me 还是 aget_py 下载文件的速度都非常慢，试过调 -s 和 -k 各种组合，但是最好的也就是一开始几秒能达到 10MB/s 左右，然后就又降到 <400KB/s。

账号是svip4，在手机app上实测能跑满带宽，应该没有黑号，并且我注册了个新号并开通了svip，在 BaiduPCS-Py 里下载速度结果还是一样。在另一个 Linux 服务器(不同IP)上使用 BaiduPCS-Py 下载，两个账号的速度也一样上不去。

然后我用 BaiduPCS-Go 下载文件，2个 Linux 服务器和我的 win10 电脑的结果，全部下载速度和 BaiduPCS-Py 一样，都跑不上去。难道是 PCS 限速了吗？

**Comment by PeterDing** [comment]
昨天我也遇到这个情况，目前不清楚是什么问题。周末我看看。

**Comment by Aixzk** [comment]
好，谢谢大佬

**Comment by PeterDing** [comment]
问题已经在 https://github.com/qjfoidnh/BaiduPCS-Go/issues/119#issuecomment-903292562 解决。
我会尽快在 `v0.6.27` 版更新。

**Comment by PeterDing** [comment]
已在 `v0.6.27` 修复。

**Comment by Aixzk** [comment]
十分谢谢
