### ISSUE TITLE
问题咨询

### ISSUE THREAD

**Issue by yzf123456** [PeterDing/BaiduPCS-Py#68]
你好，请问这个share是具体在哪里调用呢？我根据列出其他用户分享的链接的业务逻辑找了一遍，没有找到具体的调用。只定位到share.py中 shared_paths = deque(api.shared_paths(shared_url))处。谢谢啦
![image](https://user-images.githubusercontent.com/43875437/131433406-f5376e83-9ad7-41d6-b517-c79af91ef7dc.png)

**Comment by PeterDing** [comment]
是 `share` 命令入口函数吗？

**Comment by yzf123456** [comment]
> 是 `share` 命令入口函数吗？
你好，如下图所示。我在使用列出其他用户分享的链接的时候出现了该文件禁止分享的错误，然后定位到下图的代码，但是没有找到在列出其他用户分享的链接的整个业务逻辑中哪里调用了这个函数。谢谢。
![截屏2021-08-31 上午11 25 26](https://user-images.githubusercontent.com/43875437/131436870-a3b3b800-6168-4e59-9d38-8cf29a49a902.png)

**Comment by yzf123456** [comment]
![截屏2021-08-31 上午11 33 52](https://user-images.githubusercontent.com/43875437/131437570-f87bb50e-c123-4dbc-a6c2-84a3cf9a9aed.png)
我找到是这个函数调用的，但没有找到，列出其他用户分享的链接的业务代码中哪里调用了这个函数。谢谢

**Comment by PeterDing** [comment]
列出其他用户分享链接中的文件 命令 `listsharedpaths` 的入口函数在
https://github.com/PeterDing/BaiduPCS-Py/blob/b70fdddebf38a17493124970ffb3bca979d996a1/baidupcs_py/app/app.py#L1533

**Comment by yzf123456** [comment]
> 列出其他用户分享链接中的文件 命令 `listsharedpaths` 的入口函数在
> https://github.com/PeterDing/BaiduPCS-Py/blob/b70fdddebf38a17493124970ffb3bca979d996a1/baidupcs_py/app/app.py#L1533

你好，我知道这个，我好像找到问题所在了，看到您使用了断言
