### ISSUE TITLE
请问未来有机会添加一个无感知加密文件名的功能吗

### ISSUE THREAD

**Issue by tobexeon** [PeterDing/BaiduPCS-Py#78]
项目里面的无感加密功能真的很棒，但是因为不清楚百度是否会审查或者和谐含有特定关键词的文件，或者说有些含有特定字符的文件存在无法上传的情况（比如数据库内一些特定命名的文件或者带emoji的文件等等），所以一直使用的baidupcs-py+encfs的方案，但是这样就没办法实时播放视频了
加密文件名的好处有2个
1、更大程度的保护隐私规避审查
2、加密文件名的同时解决了百度网盘在文件名上对文件命名的限制
为了避免网盘内加密的文件名和正常的文件名的冲突，可以让用户指定特定的文件夹进行文件名加密/解密
如果作者有意实现这个功能，真的万分感谢。要是觉得没有这个必要的化，可以关闭这个issue，打扰了！！

**Comment by PeterDing** [comment]
使用了文件加密后也可以实时播放视频的。

使用 `BaiduPCS-Py p /path/to/file -s`，就可。这里一定要加 `-s`。

也可以开启 HTTP 服务 `BaiduPCS-Py sv`，用这个服务的文件连接播放视频。

**Comment by PeterDing** [comment]
文件名的无感加密比较难实现，因为它涉及到多个接口的处理。

**Comment by tobexeon** [comment]
了解了，感谢作者回复~

**Comment by tobexeon** [comment]
> 使用了文件加密后也可以实时播放视频的。
> 
> 使用 `BaiduPCS-Py p /path/to/file -s`，就可。这里一定要加 `-s`。
> 
> 也可以开启 HTTP 服务 `BaiduPCS-Py sv`，用这个服务的文件连接播放视频。

谢谢回复，不过我说的是encfs+baidupcs-py的解决方案下，无法实时播放，当然，这也不是这个项目的范围内的问题了。
