### ISSUE TITLE
建议: 新增文件夹大小统计

### ISSUE THREAD

**Issue by kice** [PeterDing/BaiduPCS-Py#80]
如题，希望加一个统计文件夹大小的功能。能递归统计子文件夹，统计时能够过滤特定文件（例如全部.mp4文件）。

原版客户端可以右键查看详细信息知道文件夹大小，现在被禁用了。

除了手动之外，没有找到办法统计文件夹大小的工具；油猴脚本一眼望去都是直连提取脚本。

不知道能不能加上。

**Comment by PeterDing** [comment]
这个可以有，计划下个版本加上吧

**Comment by PeterDing** [comment]
已经在 `v0.6.32` 中加入，见 `du` 命令
