### ISSUE TITLE
linux下http服务无法访问

### ISSUE THREAD

**Issue by dfmjndm** [PeterDing/BaiduPCS-Py#82]
从外部一台电脑访问对应端口显示访问被拒绝，防火墙已开放。

**Comment by PeterDing** [comment]
发一下你使用的命令

**Comment by Aixzk** [comment]
看一下 server 是否为 `127.0.0.1` ，`127.0.0.1` 是仅限本机访问，`0.0.0.0` 才是对所有 IP 开发
