### ISSUE TITLE
大佬，api.upload_slice有没有并行上传的python调用写法呀，还是只能同一时刻上传一个分片

### ISSUE THREAD

**Issue by szllzs** [PeterDing/BaiduPCS-Py#86]

**Comment by PeterDing** [comment]
见

https://github.com/PeterDing/BaiduPCS-Py/blob/6fd6fbc2818e14a5103285298a6c227d8bb0bbb8/baidupcs_py/commands/upload.py?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L376
