### ISSUE TITLE
ls 命令报错

### ISSUE THREAD

**Issue by foisonocean** [PeterDing/BaiduPCS-Py#9]
![截图](https://user-images.githubusercontent.com/15059605/107853078-f57c4a80-6e4e-11eb-8173-ee7d06872dfc.png)

**Comment by Masaiki** [comment]
问题出在Path.resolve这里 / 被转为 C:/ 的本地windows路径
将一部分Path 换为 PurePosixPath 应该能解决这个问题

**Comment by PeterDing** [comment]
@Masaiki 已经在改了，可能2020-02-15日就能解决

**Comment by Masaiki** [comment]
> @Masaiki 已经在改了，可能2020-02-15日就能解决

顺带问下 提交的 pull request 会被 merge 吗

**Comment by PeterDing** [comment]
@Masaiki
`@click.option("--xxx", prompt="xxx", hide_input=True)` 已经实现了 `getpass` 的功能，这里没必要直接用 `getpass`。
如果没有必要，#11 可以关闭了。

**Comment by Masaiki** [comment]
> @Masaiki
> `@click.option("--xxx", prompt="xxx", hide_input=True)` 已经实现了 `getpass` 的功能，这里没必要直接用 `getpass`。
> 如果没有必要，#11 可以关闭了。

这里主要是考虑到多数情况下cookies其实是带bduss的，所以我觉得这里不用`prompt`而是手动处理一下比较好
包括api那里，如果能接受str类型的cookie会方便些

**Comment by PeterDing** [comment]
@Masaiki 
1. 如果只提供 bduss，百度网盘服务器也是接受的，所有保留了 bduss 选项。只是不能分享和转存。
2. 提供给 api 的参数最好是可以静态分析的，这样可以有效的进行类型检查。

**Comment by Masaiki** [comment]
> @Masaiki
> 
> 1. 如果只提供 bduss，百度网盘服务器也是接受的，所有保留了 bduss 选项。只是不能分享和转存。
> 2. 提供给 api 的参数最好是可以静态分析的，这样可以有效的进行类型检查。

现在的情况 bduss是必填的，我改成了如果cookies包含bduss则bduss可以不填，当然只有bduss的情况也依旧可行
所以这里我用了`Union`，并将app里的str转cookie dict直接copy了过来，考虑到的是拿到的cookie是字符串格式的情况也很多

**Comment by PeterDing** [comment]
已经在 v0.5.14 版修复。

**Comment by Masaiki** [comment]
> 已经在 v0.5.14 版修复。

在windows下试了一下 ls 和 upload 还是不行
本地的path随平台 远端的path用PurePosixPath 会好一些吧

**Comment by foisonocean** [comment]
@Masaiki 我在我这里试了，`ls` 是可以的

**Comment by Masaiki** [comment]
> @Masaiki 我在我这里试了，`ls` 是可以的

我懂了 是之前缓存的pwd的缘故
